import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'fr': {
      // Navigation
      'home': 'Accueil',
      'transactions': 'Transactions',
      'accounts': 'Comptes',
      'settings': 'Paramètres',
      'stats': 'Statistiques',
      'calendar': 'Calendrier',
      'daily': 'Quotidien',
      'help': 'Aide',
      'features': 'Fonctionnalités',
      
      // Common
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'delete': 'Supprimer',
      'edit': 'Modifier',
      'add': 'Ajouter',
      'close': 'Fermer',
      'confirm': 'Confirmer',
      'search': 'Rechercher',
      'filter': 'Filtrer',
      'loading': 'Chargement...',
      'error': 'Erreur',
      'success': 'Succès',
      
      // Transactions
      'new_transaction': 'Nouvelle transaction',
      'edit_transaction': 'Modifier la transaction',
      'expense': 'Dépense',
      'income': 'Revenu',
      'transfer': 'Transfert',
      'amount': 'Montant',
      'date': 'Date',
      'time': 'Heure',
      'category': 'Catégorie',
      'account': 'Compte',
      'description': 'Description',
      'note': 'Note',
      'add_category': 'Ajouter une catégorie',
      'add_account': 'Ajouter un compte',
      
      // Settings
      'language': 'Langue',
      'theme': 'Thème',
      'currency': 'Devise',
      'select_language': 'Sélectionnez votre langue',
      'french': 'Français',
      'english': 'Anglais',
      'spanish': 'Espagnol',
      'chinese': 'Chinois',
      'malagasy': 'Malgache',
      
      // Categories
      'housing': 'Logement',
      'groceries': 'Courses',
      'restaurant': 'Restaurants',
      'transport': 'Transport',
      'leisure': 'Loisirs',
      'health': 'Santé',
      'education': 'Éducation',
      'other': 'Autres',
      'salary': 'Salaire',
      'freelance': 'Freelance',
      'investment': 'Investissements',
      'other_income': 'Autres revenus',
      
      // Transaction form
      'no_account_available': 'Aucun compte disponible',
      'create_account': 'Créer un compte',
      'select_category': 'Veuillez sélectionner une catégorie',
      'select_account': 'Veuillez sélectionner un compte',
      'enter_amount': 'Veuillez entrer un montant',
      'invalid_amount': 'Montant invalide',
      'note_description': 'Note / Description',
      'add_note': 'Ajouter une note...',
      'photos_receipts': 'Photos / Reçus',
      'camera': 'Appareil photo',
      'gallery': 'Galerie',
      'advanced_options': 'Options avancées',
      'recurring_transaction': 'Transaction récurrente',
      'repeat_transaction': 'Répéter cette transaction',
      'frequency': 'Fréquence',
      'daily': 'Quotidien',
      'weekly': 'Hebdomadaire',
      'monthly': 'Mensuel',
      'yearly': 'Annuel',
      'installment_payment': 'Paiement en plusieurs fois',
      'split_amount_months': 'Répartir le montant sur plusieurs mois',
      'installment_count': 'Nombre de versements',
      'bookmark': 'Marquer comme favori',
      'reuse_quickly': 'Réutiliser rapidement',
      'save_and_continue': 'Enregistrer et continuer',
      'transaction_saved': 'Transaction enregistrée',
      'transaction_updated': 'Transaction modifiée avec succès',
      'transaction_saved_success': 'Transaction enregistrée avec succès',
      'category_added': 'Catégorie ajoutée avec succès',
      'account_added': 'Compte ajouté avec succès',
      'from': 'De',
      'to': 'Vers',
      'category_name': 'Nom de la catégorie',
      'category_name_example': 'Ex: Vêtements',
      'icon': 'Icône',
      'account_name': 'Nom du compte',
      'account_name_example': 'Ex: Compte courant',
      'initial_balance': 'Solde initial',
      'account_type': 'Type',
      'account_category': 'Catégorie',
      'asset': 'Actif',
      'liability': 'Passif',
      'custom': 'Personnalisé',
      'bank': 'Banque',
      'cash': 'Espèces',
      'wallet': 'Portefeuille',
      'credit_card': 'Carte de crédit',
      'loan': 'Prêt',
      'savings': 'Épargne',
      'investment': 'Investissement',
      'mobile_money': 'Mobile Money',
      
      // Settings
      'appearance': 'Apparence',
      'general': 'Général',
      'dark': 'Sombre',
      'light': 'Clair',
      'start_screen': 'Écran de démarrage',
      'choose_start_screen': 'Choisir l\'écran au démarrage',
      'custom_colors': 'Couleurs personnalisées',
      'income_expense': 'Revenus / Dépenses',
      'main_currency': 'Devise principale',
      'sub_currencies': 'Sous-devises',
      'add_currencies': 'Ajouter des devises supplémentaires',
      'decimals': 'Décimales',
      'decimal': 'décimale',
      'transaction_recurrence': 'Répétition des transactions',
      'manage_recurring': 'Gérer les transactions récurrentes',
      'reminders': 'Rappels (alarme)',
      'manage_reminders': 'Gérer les rappels de dépenses',
      'filtering_search': 'Filtrage et recherche',
      'filter_options': 'Options de filtrage des transactions',
      'security': 'Sécurité',
      'code_lock': 'Verrouillage par code',
      'lock_enabled': 'Verrouillage activé',
      'protect_app': 'Protéger l\'application avec un code PIN, mot de passe ou biométrie',
      'backup': 'Sauvegarde',
      'backup_google_drive': 'Sauvegarder sur Google Drive',
      'restore': 'Restauration',
      'restore_backup': 'Restaurer depuis une sauvegarde',
      'export_data': 'Exporter les données',
      'export_formats': 'Excel, CSV, TXT',
      'advanced': 'Avancé',
      'month_start_date': 'Date de début du mois',
      'customize_budget_cycle': 'Personnaliser le cycle budgétaire',
      'subcategories': 'Sous-catégories',
      'enable_disable_subcategories': 'Activer/désactiver les sous-catégories',
      'pc_manager': 'PC Manager',
      'wifi_access': 'Voir et modifier via WiFi sur PC',
      'language_updated': 'Langue mise à jour',
      'colors_updated': 'Couleurs mises à jour',
      'currency_updated': 'Devise mise à jour',
      'select_color': 'Sélectionnez une couleur',
      'income_color': 'Couleur des revenus',
      'expense_color': 'Couleur des dépenses',
      'select_colors': 'Sélectionnez les couleurs pour les revenus et dépenses',
    },
    'en': {
      // Navigation
      'home': 'Home',
      'transactions': 'Transactions',
      'accounts': 'Accounts',
      'settings': 'Settings',
      'stats': 'Statistics',
      'calendar': 'Calendar',
      'daily': 'Daily',
      'help': 'Help',
      'features': 'Features',
      
      // Common
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'add': 'Add',
      'close': 'Close',
      'confirm': 'Confirm',
      'search': 'Search',
      'filter': 'Filter',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      
      // Transactions
      'new_transaction': 'New Transaction',
      'edit_transaction': 'Edit Transaction',
      'expense': 'Expense',
      'income': 'Income',
      'transfer': 'Transfer',
      'amount': 'Amount',
      'date': 'Date',
      'time': 'Time',
      'category': 'Category',
      'account': 'Account',
      'description': 'Description',
      'note': 'Note',
      'add_category': 'Add Category',
      'add_account': 'Add Account',
      
      // Settings
      'language': 'Language',
      'theme': 'Theme',
      'currency': 'Currency',
      'select_language': 'Select your language',
      'french': 'French',
      'english': 'English',
      'spanish': 'Spanish',
      'chinese': 'Chinese',
      'malagasy': 'Malagasy',
      
      // Categories
      'housing': 'Housing',
      'groceries': 'Groceries',
      'restaurant': 'Restaurants',
      'transport': 'Transport',
      'leisure': 'Leisure',
      'health': 'Health',
      'education': 'Education',
      'other': 'Other',
      'salary': 'Salary',
      'freelance': 'Freelance',
      'investment': 'Investments',
      'other_income': 'Other Income',
      
      // Transaction form
      'no_account_available': 'No account available',
      'create_account': 'Create account',
      'select_category': 'Please select a category',
      'select_account': 'Please select an account',
      'enter_amount': 'Please enter an amount',
      'invalid_amount': 'Invalid amount',
      'note_description': 'Note / Description',
      'add_note': 'Add a note...',
      'photos_receipts': 'Photos / Receipts',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'advanced_options': 'Advanced options',
      'recurring_transaction': 'Recurring transaction',
      'repeat_transaction': 'Repeat this transaction',
      'frequency': 'Frequency',
      'daily': 'Daily',
      'weekly': 'Weekly',
      'monthly': 'Monthly',
      'yearly': 'Yearly',
      'installment_payment': 'Installment payment',
      'split_amount_months': 'Split amount over several months',
      'installment_count': 'Number of installments',
      'bookmark': 'Bookmark',
      'reuse_quickly': 'Reuse quickly',
      'save_and_continue': 'Save and continue',
      'transaction_saved': 'Transaction saved',
      'transaction_updated': 'Transaction updated successfully',
      'transaction_saved_success': 'Transaction saved successfully',
      'category_added': 'Category added successfully',
      'account_added': 'Account added successfully',
      'from': 'From',
      'to': 'To',
      'category_name': 'Category name',
      'category_name_example': 'Ex: Clothing',
      'icon': 'Icon',
      'account_name': 'Account name',
      'account_name_example': 'Ex: Checking account',
      'initial_balance': 'Initial balance',
      'account_type': 'Type',
      'account_category': 'Category',
      'asset': 'Asset',
      'liability': 'Liability',
      'custom': 'Custom',
      'bank': 'Bank',
      'cash': 'Cash',
      'wallet': 'Wallet',
      'credit_card': 'Credit card',
      'loan': 'Loan',
      'savings': 'Savings',
      'investment': 'Investment',
      'mobile_money': 'Mobile Money',
      
      // Settings
      'appearance': 'Appearance',
      'general': 'General',
      'dark': 'Dark',
      'light': 'Light',
      'start_screen': 'Start screen',
      'choose_start_screen': 'Choose the start screen',
      'custom_colors': 'Custom colors',
      'income_expense': 'Income / Expenses',
      'main_currency': 'Main currency',
      'sub_currencies': 'Sub-currencies',
      'add_currencies': 'Add additional currencies',
      'decimals': 'Decimals',
      'decimal': 'decimal',
      'transaction_recurrence': 'Transaction recurrence',
      'manage_recurring': 'Manage recurring transactions',
      'reminders': 'Reminders (alarm)',
      'manage_reminders': 'Manage expense reminders',
      'filtering_search': 'Filtering and search',
      'filter_options': 'Transaction filtering options',
      'security': 'Security',
      'code_lock': 'Code lock',
      'lock_enabled': 'Lock enabled',
      'protect_app': 'Protect the app with a PIN, password or biometrics',
      'backup': 'Backup',
      'backup_google_drive': 'Backup to Google Drive',
      'restore': 'Restore',
      'restore_backup': 'Restore from a backup',
      'export_data': 'Export data',
      'export_formats': 'Excel, CSV, TXT',
      'advanced': 'Advanced',
      'month_start_date': 'Month start date',
      'customize_budget_cycle': 'Customize budget cycle',
      'subcategories': 'Subcategories',
      'enable_disable_subcategories': 'Enable/disable subcategories',
      'pc_manager': 'PC Manager',
      'wifi_access': 'View and edit via WiFi on PC',
      'language_updated': 'Language updated',
      'colors_updated': 'Colors updated',
      'currency_updated': 'Currency updated',
      'select_color': 'Select a color',
      'income_color': 'Income color',
      'expense_color': 'Expense color',
      'select_colors': 'Select colors for income and expenses',
    },
    'es': {
      // Navigation
      'home': 'Inicio',
      'transactions': 'Transacciones',
      'accounts': 'Cuentas',
      'settings': 'Configuración',
      'stats': 'Estadísticas',
      'calendar': 'Calendario',
      'daily': 'Diario',
      'help': 'Ayuda',
      'features': 'Características',
      
      // Common
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'edit': 'Editar',
      'add': 'Añadir',
      'close': 'Cerrar',
      'confirm': 'Confirmar',
      'search': 'Buscar',
      'filter': 'Filtrar',
      'loading': 'Cargando...',
      'error': 'Error',
      'success': 'Éxito',
      
      // Transactions
      'new_transaction': 'Nueva Transacción',
      'edit_transaction': 'Editar Transacción',
      'expense': 'Gasto',
      'income': 'Ingreso',
      'transfer': 'Transferencia',
      'amount': 'Cantidad',
      'date': 'Fecha',
      'time': 'Hora',
      'category': 'Categoría',
      'account': 'Cuenta',
      'description': 'Descripción',
      'note': 'Nota',
      'add_category': 'Añadir Categoría',
      'add_account': 'Añadir Cuenta',
      
      // Settings
      'language': 'Idioma',
      'theme': 'Tema',
      'currency': 'Moneda',
      'select_language': 'Seleccione su idioma',
      'french': 'Francés',
      'english': 'Inglés',
      'spanish': 'Español',
      'chinese': 'Chino',
      'malagasy': 'Malgache',
      
      // Categories
      'housing': 'Vivienda',
      'groceries': 'Comestibles',
      'restaurant': 'Restaurantes',
      'transport': 'Transporte',
      'leisure': 'Ocio',
      'health': 'Salud',
      'education': 'Educación',
      'other': 'Otros',
      'salary': 'Salario',
      'freelance': 'Freelance',
      'investment': 'Inversiones',
      'other_income': 'Otros Ingresos',
      
      // Transaction form
      'no_account_available': 'No hay cuenta disponible',
      'create_account': 'Crear cuenta',
      'select_category': 'Por favor seleccione una categoría',
      'select_account': 'Por favor seleccione una cuenta',
      'enter_amount': 'Por favor ingrese un monto',
      'invalid_amount': 'Monto inválido',
      'note_description': 'Nota / Descripción',
      'add_note': 'Agregar una nota...',
      'photos_receipts': 'Fotos / Recibos',
      'camera': 'Cámara',
      'gallery': 'Galería',
      'advanced_options': 'Opciones avanzadas',
      'recurring_transaction': 'Transacción recurrente',
      'repeat_transaction': 'Repetir esta transacción',
      'frequency': 'Frecuencia',
      'daily': 'Diario',
      'weekly': 'Semanal',
      'monthly': 'Mensual',
      'yearly': 'Anual',
      'installment_payment': 'Pago a plazos',
      'split_amount_months': 'Dividir el monto en varios meses',
      'installment_count': 'Número de pagos',
      'bookmark': 'Marcar como favorito',
      'reuse_quickly': 'Reutilizar rápidamente',
      'save_and_continue': 'Guardar y continuar',
      'transaction_saved': 'Transacción guardada',
      'transaction_updated': 'Transacción actualizada con éxito',
      'transaction_saved_success': 'Transacción guardada con éxito',
      'category_added': 'Categoría agregada con éxito',
      'account_added': 'Cuenta agregada con éxito',
      'from': 'De',
      'to': 'Hacia',
      'category_name': 'Nombre de la categoría',
      'category_name_example': 'Ej: Ropa',
      'icon': 'Icono',
      'account_name': 'Nombre de la cuenta',
      'account_name_example': 'Ej: Cuenta corriente',
      'initial_balance': 'Saldo inicial',
      'account_type': 'Tipo',
      'account_category': 'Categoría',
      'asset': 'Activo',
      'liability': 'Pasivo',
      'custom': 'Personalizado',
      'bank': 'Banco',
      'cash': 'Efectivo',
      'wallet': 'Billetera',
      'credit_card': 'Tarjeta de crédito',
      'loan': 'Préstamo',
      'savings': 'Ahorros',
      'investment': 'Inversión',
      'mobile_money': 'Dinero móvil',
      
      // Settings
      'appearance': 'Apariencia',
      'general': 'General',
      'dark': 'Oscuro',
      'light': 'Claro',
      'start_screen': 'Pantalla de inicio',
      'choose_start_screen': 'Elegir la pantalla de inicio',
      'custom_colors': 'Colores personalizados',
      'income_expense': 'Ingresos / Gastos',
      'main_currency': 'Moneda principal',
      'sub_currencies': 'Sub-monedas',
      'add_currencies': 'Agregar monedas adicionales',
      'decimals': 'Decimales',
      'decimal': 'decimal',
      'transaction_recurrence': 'Recurrencia de transacciones',
      'manage_recurring': 'Gestionar transacciones recurrentes',
      'reminders': 'Recordatorios (alarma)',
      'manage_reminders': 'Gestionar recordatorios de gastos',
      'filtering_search': 'Filtrado y búsqueda',
      'filter_options': 'Opciones de filtrado de transacciones',
      'security': 'Seguridad',
      'code_lock': 'Bloqueo con código',
      'lock_enabled': 'Bloqueo activado',
      'protect_app': 'Proteger la aplicación con PIN, contraseña o biometría',
      'backup': 'Respaldo',
      'backup_google_drive': 'Respaldar en Google Drive',
      'restore': 'Restaurar',
      'restore_backup': 'Restaurar desde un respaldo',
      'export_data': 'Exportar datos',
      'export_formats': 'Excel, CSV, TXT',
      'advanced': 'Avanzado',
      'month_start_date': 'Fecha de inicio del mes',
      'customize_budget_cycle': 'Personalizar ciclo presupuestario',
      'subcategories': 'Subcategorías',
      'enable_disable_subcategories': 'Activar/desactivar subcategorías',
      'pc_manager': 'Administrador PC',
      'wifi_access': 'Ver y editar vía WiFi en PC',
      'language_updated': 'Idioma actualizado',
      'colors_updated': 'Colores actualizados',
      'currency_updated': 'Moneda actualizada',
      'select_color': 'Seleccione un color',
      'income_color': 'Color de ingresos',
      'expense_color': 'Color de gastos',
      'select_colors': 'Seleccione los colores para ingresos y gastos',
    },
    'zh': {
      // Navigation
      'home': '首页',
      'transactions': '交易',
      'accounts': '账户',
      'settings': '设置',
      'stats': '统计',
      'calendar': '日历',
      'daily': '每日',
      'help': '帮助',
      'features': '功能',
      
      // Common
      'save': '保存',
      'cancel': '取消',
      'delete': '删除',
      'edit': '编辑',
      'add': '添加',
      'close': '关闭',
      'confirm': '确认',
      'search': '搜索',
      'filter': '筛选',
      'loading': '加载中...',
      'error': '错误',
      'success': '成功',
      
      // Transactions
      'new_transaction': '新交易',
      'edit_transaction': '编辑交易',
      'expense': '支出',
      'income': '收入',
      'transfer': '转账',
      'amount': '金额',
      'date': '日期',
      'time': '时间',
      'category': '类别',
      'account': '账户',
      'description': '描述',
      'note': '备注',
      'add_category': '添加类别',
      'add_account': '添加账户',
      
      // Settings
      'language': '语言',
      'theme': '主题',
      'currency': '货币',
      'select_language': '选择您的语言',
      'french': '法语',
      'english': '英语',
      'spanish': '西班牙语',
      'chinese': '中文',
      'malagasy': '马达加斯加语',
      
      // Categories
      'housing': '住房',
      'groceries': '杂货',
      'restaurant': '餐厅',
      'transport': '交通',
      'leisure': '休闲',
      'health': '健康',
      'education': '教育',
      'other': '其他',
      'salary': '工资',
      'freelance': '自由职业',
      'investment': '投资',
      'other_income': '其他收入',
      
      // Transaction form
      'no_account_available': '没有可用账户',
      'create_account': '创建账户',
      'select_category': '请选择类别',
      'select_account': '请选择账户',
      'enter_amount': '请输入金额',
      'invalid_amount': '金额无效',
      'note_description': '备注 / 描述',
      'add_note': '添加备注...',
      'photos_receipts': '照片 / 收据',
      'camera': '相机',
      'gallery': '图库',
      'advanced_options': '高级选项',
      'recurring_transaction': '定期交易',
      'repeat_transaction': '重复此交易',
      'frequency': '频率',
      'daily': '每日',
      'weekly': '每周',
      'monthly': '每月',
      'yearly': '每年',
      'installment_payment': '分期付款',
      'split_amount_months': '将金额分摊到几个月',
      'installment_count': '分期数',
      'bookmark': '标记为收藏',
      'reuse_quickly': '快速重用',
      'save_and_continue': '保存并继续',
      'transaction_saved': '交易已保存',
      'transaction_updated': '交易更新成功',
      'transaction_saved_success': '交易保存成功',
      'category_added': '类别添加成功',
      'account_added': '账户添加成功',
      'from': '从',
      'to': '到',
      'category_name': '类别名称',
      'category_name_example': '例如：服装',
      'icon': '图标',
      'account_name': '账户名称',
      'account_name_example': '例如：活期账户',
      'initial_balance': '初始余额',
      'account_type': '类型',
      'account_category': '类别',
      'asset': '资产',
      'liability': '负债',
      'custom': '自定义',
      'bank': '银行',
      'cash': '现金',
      'wallet': '钱包',
      'credit_card': '信用卡',
      'loan': '贷款',
      'savings': '储蓄',
      'investment': '投资',
      'mobile_money': '移动支付',
      
      // Settings
      'appearance': '外观',
      'general': '常规',
      'dark': '深色',
      'light': '浅色',
      'start_screen': '启动屏幕',
      'choose_start_screen': '选择启动屏幕',
      'custom_colors': '自定义颜色',
      'income_expense': '收入 / 支出',
      'main_currency': '主货币',
      'sub_currencies': '子货币',
      'add_currencies': '添加其他货币',
      'decimals': '小数位',
      'decimal': '小数',
      'transaction_recurrence': '交易重复',
      'manage_recurring': '管理定期交易',
      'reminders': '提醒（闹钟）',
      'manage_reminders': '管理支出提醒',
      'filtering_search': '筛选和搜索',
      'filter_options': '交易筛选选项',
      'security': '安全',
      'code_lock': '代码锁定',
      'lock_enabled': '锁定已启用',
      'protect_app': '使用PIN、密码或生物识别保护应用',
      'backup': '备份',
      'backup_google_drive': '备份到Google Drive',
      'restore': '恢复',
      'restore_backup': '从备份恢复',
      'export_data': '导出数据',
      'export_formats': 'Excel, CSV, TXT',
      'advanced': '高级',
      'month_start_date': '月初日期',
      'customize_budget_cycle': '自定义预算周期',
      'subcategories': '子类别',
      'enable_disable_subcategories': '启用/禁用子类别',
      'pc_manager': 'PC管理器',
      'wifi_access': '通过WiFi在PC上查看和编辑',
      'language_updated': '语言已更新',
      'colors_updated': '颜色已更新',
      'currency_updated': '货币已更新',
      'select_color': '选择颜色',
      'income_color': '收入颜色',
      'expense_color': '支出颜色',
      'select_colors': '选择收入和支出的颜色',
    },
    'mg': {
      // Navigation
      'home': 'Fandraisana',
      'transactions': 'Fivarotana',
      'accounts': 'Kaonty',
      'settings': 'Fikirana',
      'stats': 'Statistika',
      'calendar': 'Kalandrie',
      'daily': 'Isan\'andro',
      'help': 'Fanampiana',
      'features': 'Toetra',
      
      // Common
      'save': 'Tehirizina',
      'cancel': 'Avelao',
      'delete': 'Fafana',
      'edit': 'Ovaina',
      'add': 'Ampidirina',
      'close': 'Akatona',
      'confirm': 'Manamarina',
      'search': 'Mitady',
      'filter': 'Sivana',
      'loading': 'Miandry...',
      'error': 'Hadisoana',
      'success': 'Fahombiazana',
      
      // Transactions
      'new_transaction': 'Fivarotana Vaovao',
      'edit_transaction': 'Ovaina ny Fivarotana',
      'expense': 'Fandaniana',
      'income': 'Fidirana',
      'transfer': 'Famindrana',
      'amount': 'Vola',
      'date': 'Daty',
      'time': 'Ora',
      'category': 'Sokajy',
      'account': 'Kaonty',
      'description': 'Famaritana',
      'note': 'Fanamarihana',
      'add_category': 'Ampidirina Sokajy',
      'add_account': 'Ampidirina Kaonty',
      
      // Settings
      'language': 'Fiteny',
      'theme': 'Lohahevitra',
      'currency': 'Vola',
      'select_language': 'Fidio ny fiteninao',
      'french': 'Frantsay',
      'english': 'Anglisy',
      'spanish': 'Espaniola',
      'chinese': 'Sinoa',
      'malagasy': 'Malagasy',
      
      // Categories
      'housing': 'Trano',
      'groceries': 'Fivarotana',
      'restaurant': 'Restaurant',
      'transport': 'Fiara',
      'leisure': 'Fialamboly',
      'health': 'Fahasalamana',
      'education': 'Fampianarana',
      'other': 'Hafa',
      'salary': 'Karama',
      'freelance': 'Freelance',
      'investment': 'Fampiasam-bola',
      'other_income': 'Fidirana Hafa',
      
      // Transaction form
      'no_account_available': 'Tsy misy kaonty',
      'create_account': 'Mamorona kaonty',
      'select_category': 'Mifidiana sokajy',
      'select_account': 'Mifidiana kaonty',
      'enter_amount': 'Ampidiro ny vola',
      'invalid_amount': 'Vola tsy mety',
      'note_description': 'Fanamarihana / Famaritana',
      'add_note': 'Ampidiro famanamarihana...',
      'photos_receipts': 'Sary / Tapakila',
      'camera': 'Fakan-tsary',
      'gallery': 'Gallery',
      'advanced_options': 'Safidy avo lenta',
      'recurring_transaction': 'Fivarotana miverimberina',
      'repeat_transaction': 'Avereno ity fivarotana',
      'frequency': 'Fahafahana',
      'daily': 'Isan\'andro',
      'weekly': 'Isan-kerinandro',
      'monthly': 'Isam-bolana',
      'yearly': 'Isan-taona',
      'installment_payment': 'Fandoavana amin\'ny ampahany',
      'split_amount_months': 'Zarao ny vola amin\'ny volana maro',
      'installment_count': 'Isan\'ny fandoavana',
      'bookmark': 'Marika ho an\'ny tiana',
      'reuse_quickly': 'Ampiasaina haingana',
      'save_and_continue': 'Tehirizina sy manohy',
      'transaction_saved': 'Fivarotana voatahiry',
      'transaction_updated': 'Fivarotana novaina soa aman-tsara',
      'transaction_saved_success': 'Fivarotana voatahiry soa aman-tsara',
      'category_added': 'Sokajy nampidirina soa aman-tsara',
      'account_added': 'Kaonty nampidirina soa aman-tsara',
      'from': 'Avy',
      'to': 'Ho any',
      'category_name': 'Anaran\'ny sokajy',
      'category_name_example': 'Ohatra: Akanjo',
      'icon': 'Ikonina',
      'account_name': 'Anaran\'ny kaonty',
      'account_name_example': 'Ohatra: Kaonty mahazatra',
      'initial_balance': 'Vola voalohany',
      'account_type': 'Karazana',
      'account_category': 'Sokajy',
      'asset': 'Harena',
      'liability': 'Trosa',
      'custom': 'Manokana',
      'bank': 'Banky',
      'cash': 'Vola',
      'wallet': 'Pitaka',
      'credit_card': 'Kartin\'ny trosa',
      'loan': 'Trosa',
      'savings': 'Fitehirizana',
      'investment': 'Fampiasam-bola',
      'mobile_money': 'Vola finday',
      
      // Settings
      'appearance': 'Endrika',
      'general': 'Ankapobeny',
      'dark': 'Maizina',
      'light': 'Mazava',
      'start_screen': 'Efijery voalohany',
      'choose_start_screen': 'Mifidiana efijery voalohany',
      'custom_colors': 'Loko manokana',
      'income_expense': 'Fidirana / Fandaniana',
      'main_currency': 'Vola lehibe',
      'sub_currencies': 'Vola faharoa',
      'add_currencies': 'Ampidiro vola hafa',
      'decimals': 'Isan\'ny desimaly',
      'decimal': 'desimaly',
      'transaction_recurrence': 'Fiverenan\'ny fivarotana',
      'manage_recurring': 'Tantano ny fivarotana miverimberina',
      'reminders': 'Fahatsiarovana (alarma)',
      'manage_reminders': 'Tantano ny fahatsiarovana fandaniana',
      'filtering_search': 'Sivana sy fitadiavana',
      'filter_options': 'Safidy sivana fivarotana',
      'security': 'Fiarovana',
      'code_lock': 'Famatorana amin\'ny kaody',
      'lock_enabled': 'Famatorana nampandeha',
      'protect_app': 'Arovy ny app amin\'ny PIN, teny miafina na biometrika',
      'backup': 'Fitehirizana',
      'backup_google_drive': 'Tehirizo ao amin\'ny Google Drive',
      'restore': 'Averina',
      'restore_backup': 'Averina avy amin\'ny fitehirizana',
      'export_data': 'Avoaka ny angona',
      'export_formats': 'Excel, CSV, TXT',
      'advanced': 'Avo lenta',
      'month_start_date': 'Daty voalohany amin\'ny volana',
      'customize_budget_cycle': 'Ampifanaraho ny tsingerin\'ny tetibola',
      'subcategories': 'Sokajy faharoa',
      'enable_disable_subcategories': 'Ampandeha/ampitsahatra ny sokajy faharoa',
      'pc_manager': 'Mpandrindra PC',
      'wifi_access': 'Jereo sy ovay amin\'ny WiFi amin\'ny PC',
      'language_updated': 'Fiteny novaina',
      'colors_updated': 'Loko novaina',
      'currency_updated': 'Vola novaina',
      'select_color': 'Mifidiana loko',
      'income_color': 'Loko fidirana',
      'expense_color': 'Loko fandaniana',
      'select_colors': 'Mifidiana loko ho an\'ny fidirana sy fandaniana',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? 
           _localizedValues['fr']?[key] ?? 
           key;
  }

  // Helper methods for common translations
  String get home => translate('home');
  String get transactions => translate('transactions');
  String get accounts => translate('accounts');
  String get settings => translate('settings');
  String get save => translate('save');
  String get cancel => translate('cancel');
  String get delete => translate('delete');
  String get edit => translate('edit');
  String get add => translate('add');
  String get close => translate('close');
  String get language => translate('language');
  String get newTransaction => translate('new_transaction');
  String get editTransaction => translate('edit_transaction');
  String get expense => translate('expense');
  String get income => translate('income');
  String get transfer => translate('transfer');
  String get amount => translate('amount');
  String get date => translate('date');
  String get time => translate('time');
  String get category => translate('category');
  String get account => translate('account');
  String get description => translate('description');
  String get note => translate('note');
  String get addCategory => translate('add_category');
  String get addAccount => translate('add_account');
  String get error => translate('error');
  String get daily => translate('daily');
  String get calendar => translate('calendar');
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['fr', 'en', 'es', 'zh', 'mg'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

